name: "Build MRS by Compiling from Source"

on:
  push:
    branches: [ main ]
    paths:
      - 'rulesets/**'
  
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-mrs
  cancel-in-progress: true

jobs:
  build-mrs:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出您自己的仓库代码
      - name: Checkout Your Repository
        uses: actions/checkout@v4

      # 2. 【核心步骤】设置 Go 环境并从源代码编译 mrs-generator
      - name: Build mrs-generator from Source
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # 指定 Go 版本
      - run: |
          echo "Cloning mrs-generator source code..."
          # 克隆一个当前可用的源代码仓库
          git clone https://github.com/KOP-XIAO/mrs-generator.git temp-mrs-generator
          
          cd temp-mrs-generator
          
          echo "Compiling the tool..."
          # 编译 Go 程序
          go build -o ../mrs-generator .
          
          cd ..
          
          # 创建 tools 目录并将编译好的工具放进去
          mkdir -p tools
          mv mrs-generator tools/
          
          # 清理临时文件
          rm -rf temp-mrs-generator

      # 3. 验证并转换 TXT 为 MRS
      - name: Convert TXT to MRS
        shell: bash
        run: |
          # 检查工具是否成功编译
          if [ ! -f "tools/mrs-generator" ]; then
            echo "::error::Failed to build mrs-generator from source!"
            exit 1
          fi

          # 赋予可执行权限
          chmod +x tools/mrs-generator
          
          # 查找并转换所有 .txt 文件
          find rulesets -type f -name "*.txt" | while read -r in_file; do
            out_file=$(echo "$in_file" | sed 's|^rulesets/|mrs-rules/|' | sed 's|\.txt$|.mrs|')
            echo "Converting: $in_file  ==>  $out_file"
            mkdir -p "$(dirname "$out_file")"
            ./tools/mrs-generator -i "$in_file" -o "$out_file"
          done

      # 4. 提交生成的 MRS 文件
      - name: Commit and Push MRS files
        run: |
          if [[ -z $(git status --porcelain mrs-rules) ]]; then
            echo "No changes to MRS files. Nothing to commit."
            exit 0
          fi
          
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'
          git add mrs-rules/
          git commit -m "chore(mrs): Auto-build MRS files"
          git push
