name: "Generate README for MRS (fast, no link check)"

on:
  push:
    branches: [ main ]
    paths:
      - "mrs-rules/**"
      - "scripts/gen-readme-fast.sh"
  workflow_dispatch:
    inputs:
      ref:
        description: "Links base ref (default: main)"
        required: false
        type: string
      cdn:
        description: "CDN for example in README (jsdelivr/raw)"
        required: false
        default: "jsdelivr"
        type: choice
        options: ["jsdelivr", "raw"]

permissions:
  contents: write

concurrency:
  group: gen-readme-fast
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history for rebase)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'

      - name: Rebase to latest main
        shell: bash
        run: |
          set -euo pipefail
          BRANCH="${GITHUB_REF_NAME:-main}"
          git fetch origin "$BRANCH"
          git checkout "$BRANCH"
          git pull --rebase origin "$BRANCH"

      - name: Make generator executable
        run: chmod +x scripts/gen-readme-fast.sh

      - name: Normalize line endings (LF) for script
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dos2unix
          dos2unix scripts/gen-readme-fast.sh || true

      - name: Bash syntax check
        run: bash -n scripts/gen-readme-fast.sh

      - name: Generate README (fast)
        env:
          INPUT_REF: ${{ inputs.ref || 'main' }}
          INPUT_CDN: ${{ inputs.cdn || 'jsdelivr' }}
          # 可选调优（保持不配即与旧逻辑完全一致）
          # MRS_JOBS: "2"
          # SNIFF_MAX: "0"              # 若设为 "200" 可明显提速
          # SHORTCIRCUIT_BY_PATH: "false"
          # PROGRESS_EVERY: "5"
          # VERBOSE_PROGRESS: "true"
        run: scripts/gen-readme-fast.sh

      - name: Commit README changes (if any)
        id: commit
        shell: bash
        run: |
          set -euo pipefail
          if git diff --quiet README.md; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No README changes."
            exit 0
          fi
          git add README.md
          git commit -m "docs(readme): auto-update (mrs index, fast) at $(date +'%Y-%m-%d %H:%M:%S %Z')"
          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Push with rebase retry
        if: steps.commit.outputs.changed == 'true'
        shell: bash
        run: |
          set -euo pipefail
          BRANCH="${GITHUB_REF_NAME:-main}"
          if git push origin "$BRANCH"; then
            exit 0
          fi
          echo "Non-fast-forward, rebasing and retrying..."
          git pull --rebase origin "$BRANCH"
          git push origin "$BRANCH" || {
            echo "::error::Failed to push after rebase retry."
            exit 1
          }
